### ISSUE TITLE
Paramak in the requirements somewhere?

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [fusion-energy/paramak-neutronics#3]
Would the pip install of paramak-neutronics work without installing paramak first?

I don't see it in the requirements.

**Comment by Shimwell** [comment]
Good spot thanks for that.


Ultimately both will become conda installs as not everything is available via pip

**Comment by Shimwell** [comment]
Fixing this in #13

**Comment by Shimwell** [comment]
Now merged into main
